
import jsPDF from "jspdf";

export const usePdfExport = () => {
  const exportToPdf = (content, filename = "NyayaAI_Document") => {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = margin;

    // Header
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, pageWidth, 20, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("NyayaAI — Legal Document", margin, 13);
    y = 30;

    // Clean markdown from content
    const cleanContent = content
      .replace(/\*\*(.*?)\*\*/g, "$1")   // remove bold
      .replace(/\*(.*?)\*/g, "$1")        // remove italic
      .replace(/#{1,6}\s/g, "")           // remove headings
      .replace(/─+/g, "─────────────────────────────────") // keep dividers
      .trim();

    const lines = cleanContent.split("\n");

    doc.setTextColor(20, 20, 20);

    lines.forEach((line) => {
      const trimmed = line.trim();

      // Add new page if needed
      if (y > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }

      // Divider line
      if (trimmed.startsWith("═") || trimmed.startsWith("─") || trimmed === "---") {
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageWidth - margin, y);
        y += 5;
        return;
      }

      // Section title (ALL CAPS lines)
      if (trimmed === trimmed.toUpperCase() && trimmed.length > 3 && !trimmed.startsWith("•")) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(10, 10, 10);
        const wrapped = doc.splitTextToSize(trimmed, maxWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 6 + 2;
        return;
      }

      // Subject line
      if (trimmed.startsWith("Subject:")) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(30, 30, 30);
        const wrapped = doc.splitTextToSize(trimmed, maxWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 5 + 2;
        return;
      }

      // Numbered points
      if (/^\d+\./.test(trimmed)) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(40, 40, 40);
        const wrapped = doc.splitTextToSize(trimmed, maxWidth - 5);
        doc.text(wrapped, margin + 3, y);
        y += wrapped.length * 5 + 1;
        return;
      }

      // Empty line
      if (trimmed === "") {
        y += 3;
        return;
      }

      // Normal text
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      const wrapped = doc.splitTextToSize(trimmed, maxWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 5 + 1;
    });

    // Footer on every page
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.setFont("helvetica", "italic");
      doc.text(
        "⚠️ Generated by NyayaAI. Please verify with a legal professional before submission.",
        margin,
        pageHeight - 10
      );
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 10);
    }

    doc.save(`${filename}.pdf`);
  };

  return { exportToPdf };
};